package org.apache.cayenne.testdo.compoundpk.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.compoundpk.PaymentNoPk;

/**
 * Class _OrderNoPK was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OrderNoPK extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ORDER_NUMBER_PK_COLUMN = "order_number";

    public static final Property<String> VALUE = Property.create("value", String.class);
    public static final Property<List<PaymentNoPk>> PAYMENTS = Property.create("payments", List.class);

    protected String value;

    protected Object payments;

    public void setValue(String value) {
        beforePropertyWrite("value", this.value, value);
        this.value = value;
    }

    public String getValue() {
        beforePropertyRead("value");
        return this.value;
    }

    public void addToPayments(PaymentNoPk obj) {
        addToManyTarget("payments", obj, true);
    }

    public void removeFromPayments(PaymentNoPk obj) {
        removeToManyTarget("payments", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PaymentNoPk> getPayments() {
        return (List<PaymentNoPk>)readProperty("payments");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "value":
                return this.value;
            case "payments":
                return this.payments;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "value":
                this.value = (String)val;
                break;
            case "payments":
                this.payments = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.value);
        out.writeObject(this.payments);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.value = (String)in.readObject();
        this.payments = in.readObject();
    }

}
