package org.apache.cayenne.testdo.compoundpk.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.compoundpk.PaymentNoPk;

/**
 * Class _OrderNoPK was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OrderNoPK extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ORDER_NUMBER_PK_COLUMN = "order_number";

    public static final Property<String> VALUE = Property.create("value", String.class);
    public static final Property<List<PaymentNoPk>> PAYMENTS = Property.create("payments", List.class);

    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }

    public void addToPayments(PaymentNoPk obj) {
        addToManyTarget("payments", obj, true);
    }
    public void removeFromPayments(PaymentNoPk obj) {
        removeToManyTarget("payments", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PaymentNoPk> getPayments() {
        return (List<PaymentNoPk>)readProperty("payments");
    }


}
