package org.apache.cayenne.testdo.compoundpk.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.compoundpk.PaymentPkFk;

/**
 * Class _OrderPkFk was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OrderPkFk extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ORDER_NUMBER_PK_COLUMN = "order_number";

    public static final Property<Integer> ORDER_NUMBER = Property.create("orderNumber", Integer.class);
    public static final Property<String> VALUE = Property.create("value", String.class);
    public static final Property<List<PaymentPkFk>> PAYMENTS = Property.create("payments", List.class);

    protected Integer orderNumber;
    protected String value;

    protected Object payments;

    public void setOrderNumber(Integer orderNumber) {
        beforePropertyWrite("orderNumber", this.orderNumber, orderNumber);
        if(this.objectId != null) {
            this.objectId.getReplacementIdMap().put("order_number", orderNumber);
        }
        this.orderNumber = orderNumber;
    }

    public Integer getOrderNumber() {
        beforePropertyRead("orderNumber");
        return this.orderNumber;
    }

    public void setValue(String value) {
        beforePropertyWrite("value", this.value, value);
        this.value = value;
    }

    public String getValue() {
        beforePropertyRead("value");
        return this.value;
    }

    public void addToPayments(PaymentPkFk obj) {
        addToManyTarget("payments", obj, true);
    }

    public void removeFromPayments(PaymentPkFk obj) {
        removeToManyTarget("payments", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PaymentPkFk> getPayments() {
        return (List<PaymentPkFk>)readProperty("payments");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "orderNumber":
                return this.orderNumber;
            case "value":
                return this.value;
            case "payments":
                return this.payments;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "orderNumber":
                this.orderNumber = (Integer)val;
                break;
            case "value":
                this.value = (String)val;
                break;
            case "payments":
                this.payments = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.orderNumber);
        out.writeObject(this.value);
        out.writeObject(this.payments);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.orderNumber = (Integer)in.readObject();
        this.value = (String)in.readObject();
        this.payments = in.readObject();
    }

}
