package org.apache.cayenne.testdo.compoundpk.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.compoundpk.OrderMasterPk;

/**
 * Class _PaymentMasterPk was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaymentMasterPk extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ORDER_NUMBER_PK_COLUMN = "order_number";
    public static final String PAYMENT_NUMBER_PK_COLUMN = "payment_number";

    public static final Property<BigDecimal> AMOUNT = Property.create("amount", BigDecimal.class);
    public static final Property<OrderMasterPk> ORDER = Property.create("order", OrderMasterPk.class);

    public void setAmount(BigDecimal amount) {
        writeProperty("amount", amount);
    }
    public BigDecimal getAmount() {
        return (BigDecimal)readProperty("amount");
    }

    public void setOrder(OrderMasterPk order) {
        setToOneTarget("order", order, true);
    }

    public OrderMasterPk getOrder() {
        return (OrderMasterPk)readProperty("order");
    }


}
