package org.apache.cayenne.testdo.inheritance.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance.BaseEntity;

/**
 * Class _ToManyRelatedEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ToManyRelatedEntity extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<BaseEntity> BASE_ENTITY = Property.create("baseEntity", BaseEntity.class);

    public void setBaseEntity(BaseEntity baseEntity) {
        setToOneTarget("baseEntity", baseEntity, true);
    }

    public BaseEntity getBaseEntity() {
        return (BaseEntity)readProperty("baseEntity");
    }


}
